<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class SpecialtySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $specialties = [
            'Adult Pulmonary Medicine' => [
                'Adult Bronchoscopy',
                'Interstitial Lung Disease',
                'Interventional Pulmonology',
                'Occupational Lung Disease',
                'Pediatric Pulmonary',
                'Pulmonary Critical Care',
                'Pulmonary Rehabilitation',
                'Pulmonary Vascular Disease',
                'Sleep Medicine',
            ],
            'Anatomic Pathology' => [
                'Autopsy And Forensic Pathology',
                'Breast Pathology',
                'Cytopathology',
                'Dermatopathology',
                'Gastrointestinal And Liver Pathology',
                'Gynecologic Pathology',
                'Hematopathology',
                'Immunopathology',
                'Neuropathology',
                'Renal Pathology',
                'Surgical Pathology',
                'Urologic Pathology (Male Genital Tract)',
            ],
            'Anesthesiology' => [
                'Ambulatory Anesthesia',
                'Critical Care Anesthesia',
                'Neurosurgical Anesthesia',
                'Obstetric Anesthesia',
                'Ophthalmological Anesthesia',
                'Pediatric Anesthesia',
                'Thoracic-Cardiovascular Anesthesia',
                'Transplant Anesthesia',
            ],
            'Cardiology' => [
                'Cardiac Catheterization',
                'Cardiac Radiology',
                'Cardiac Rehabilitation',
                'Cardiovascular Critical Care',
                'Echocardiography',
                'Electrophysiology And Cardiac Pacing',
                'Hypertension',
                'Interventional Cardiology',
                'Invasive Cardiology',
                'Non-Invasive Cardiac Imaging',
                'Nuclear Cardiology',
                'Peripheral And Vascular Intervention',
                'Peripheral And Vascular Medicine',
            ],
            'Clinical Pathology' => [
                'Blood Bank And Transfusion',
                'Cellular Immunology',
                'Clinical Chemistry And Toxicology',
                'Clinical Microscopy And Parasitology',
                'Hematology1',
                'Microbiology - Bacteriology',
                'Microbiology - Mycology',
                'Microbiology - Virology',
                'Phlebotomy',
                'Serology',
            ],
            'Dentistry And Oral Surgery' => [
                'Endodontics',
                'Implant Dentistry',
                'Oral And Maxillofacial Pathology',
                'Oral And Maxillofacial Radiology',
                'Oral And Maxillofacial Surgery',
                'Orthodontics And Dentofacial Orthopedics',
                'Pediatric Dentistry',
                'Prosthodontics',
                'Tmj Specialty',
            ],
            'Dermatology' => [
                'Cosmetic And Dermatologic Surgery',
                'Dermatoepidemiology',
                'Dermatologic Laser Surgery',
                'Dermatopathology',
                'Dermatopharmacology',
                'Environmental And Occupational Dermatology',
                'Hair Disorders',
                'Immunodermatology',
                'Micrographic Surgery (Mohs)',
                'Pediatric Dermatology',
                'Skin Aging',
            ],
            'Emergency Medicine' => [
                'Adult Emergency Medicine',
                'Pediatric Emergency Medicine',
            ],
            'Gastroenterology' => [
                'Diagnostic And Therapeutic Endoscopy',
                'Elastography',
                'Endoscopic Ultrasound And Ercp',
                'Hepatology',
                'Interventional Hepatology',
                'Manometry',
                'Motility Study',
                'Transplant Hepatology',
            ],
            'Hematology' => [
                'Adult Hemaoncology',
                'Adult Hematology',
                'Bone Marrow Transplant',
                'Hemopathology',
                'Pediatric Hemaoncology',
            ],
            'Infectious Disease And Tropical Medicine' => [
                'Microbiology',
                'Parasitology',
            ],
            'Internal Medicine' => [
                'Critical Care Medicine',
            ],
            'Medical Oncology' => [
                'Oncology',
            ],
            'Neurology' => [
                'Adult Neurology',
                'Clinical Neurophysiology',
                'Dementia',
                'Epilepsy',
                'Headache',
                'Medical Neurooncology',
                'Movement Disorders',
                'Neuro Critical Care',
                'Neuro-Oncology',
                'Neurodevelopmental Disorders',
                'Neuromuscular Disease',
                'Pediatric Neurology',
                'Sleep Disorders',
                'Stroke',
            ],
            'Neurosurgery' => [
                'Cerebrovascular Surgery',
                'Endovascular Neurosurgery',
                'Functional/Epilepsy Neurosurgery',
                'Image-Guided Neurosurgery',
                'Minimally Invasive Neurosurgery (Endoscopic Neurosurgery)',
                'Neuroradiology',
                'Pediatric Neurosurgery',
                'Peripheral Nerve Neurosurgery',
                'Skull Base Surgery',
                'Spine Surgery',
                'Stereotactic Radiosurgery',
                'Surgical Neurooncology',
            ],
            'Obstetrics Gynecology' => [
                'Advanced Pelvic Surgery',
                'Climacteric Medicine',
                'Cosmetic Gynecology',
                'Gestational Trophoblastic',
                'Gynecologic Minimally Invasive Surgery (Gynecologic Endoscopy And Laparoscopy)',
                'Gynecologic Oncology',
                'Lactation Medicine',
                'Maternal And Fetal Medicine (Perinatology)',
                'Obstetric Gynecologic Infectious Disease',
                'Obstetric Gynecologic Ultrasound',
                'Pediatric And Adolescent Gynecology',
                'Reproductive Endocrinology And Infertility',
                'Robotic And Minimally Invasive Obgyne',
                'Trophoblastic Disease',
                'Urogynecology',
            ],
            'Ophthalmology' => [
                'Cataract And Lens Surgery',
                'Contact Lens',
                'Cornea And External Disease',
                'Eye Banking And Corneal Transplant',
                'Glaucoma',
                'Low Vision',
                'Neuro-Ophthalmology',
                'Ocular Immunology And Uveitis',
                'Ocular Oncology',
                'Ocular Pathology And Oncology',
                'Ophthalmic Genetics',
                'Ophthalmic Plastic, Reconstructive And Orbit Surgery',
                'Pediatric Ophthalmology And Strabismus',
                'Refractive Surgery',
                'Retina And Vitreous Surgery',
            ],
            'Orthopedic Surgery' => [
                'Arthroscopy And Sports Surgery',
                'Bone/Tissue Banking',
                'Cartilage Transplant Surgery',
                'Foot And Ankle Surgery',
                'Hand Surgery',
                'Joint Replacement Surgery',
                'Limb Lengthening And Reconstruction Surgery',
                'Microvascular And Brachial Plexus Surgery',
                'Musculoskeletal Oncology',
                'Orthopedic Navigational Surgery',
                'Orthopedic Rehabilitation',
                'Orthopedic Trauma',
                'Pediatric Orthopedic Surgery',
                'Spine Surgery',
                'Sports Medicine',
            ],
            'Otorhinolaryngology And Head And Neck Surgery' => [
                'Carniomaxillofacial Surgery',
                'Facial Cosmetic Surgery',
                'Head And Neck Oncologic Surgery',
                'Hearing Balance Disorder',
                'Laryngology And Phoniatics',
                'Laryngology Bronco-Esophagology',
                'Maxillofacial Prosthetics',
                'Microvascular Reconstructive Surgery',
                'Neuro-Otology',
                'Pediatric Otorhinolaryngology',
                'Rhinopharyngology (Nose And Paranasal Sinuses)',
                'Robotic And Minimally Invasive Enth',
                'Sleep Medicine And Surgery',
            ],
            'Pain Management' => [
                'Medical Acupuncture',
                'Palliative Medicine',
                'Pediatric Pain Management',
            ],
            'Paramedical' => [
                'Adult Psychology',
                'Clinical Psychology',
                'Cognitive Psychology',
                'Music Therapy',
                'Neuropsychology',
                'Occupational Therapy',
                'Perfusionist',
                'Physical Therapy',
                'Reading Specialist',
                'School Psychology',
                'Special Education',
                'Speech And Language Pathology',
            ],
            'Pathology' => [
                'Anatomic Pathology',
                'Head And Neck - Endocrinology',
            ],
            'Pediatrics' => [
                'Adolescent Pediatrics',
                'Ambulatory Pediatrics',
                'Child Protection',
                'Developmental Pediatrics',
                'Genetics',
                'Lactation Medicine',
                'Neonatology',
                'Neurodevelopmental Pediatrics',
                'Pediatric Allergology And Immunology',
                'Pediatric Bronchology',
                'Pediatric Cardiology - Interventional',
                'Pediatric Cardiology - Invasive',
                'Pediatric Critical Care',
                'Pediatric Emergency Medicine',
                'Pediatric Endocrinology',
                'Pediatric Gastroenterology',
                'Pediatric Hematology',
                'Pediatric Infectious Disease',
                'Pediatric Nephrology',
                'Pediatric Neurology Epilepsy',
                'Pediatric Oncology',
                'Pediatric Pulmonology',
                'Pediatric Rheumatology',
                'Pediatric Sleep Medicine',
                'Pediatric Toxicology',
                'Pediatric Cardiology',
            ],
            'Psychiatry' => [
                'Addiction Psychiatry',
                'Child And Adolescent Psychiatry',
                'Consultation-Liaison Psychiatry',
                'General Adult Psychiatry',
                'Geriatric Psychiatry',
            ],
            'Radiation Oncology' => [
                'Radiation Oncology',
            ],
            'Radiology' => [
                'Breast Imaging',
                'Chest Radiology',
                'Ct Mri',
                'Diagnostic Radiology',
                'Interventional Radiology',
                'Musculoskeletal Radiology',
                'Neuroradiology Radio',
                'Pediatric Radiology',
                'Ultrasound',
            ],
            'Surgery' => [
                'Bariatric Surgery',
                'Breast Surgery',
                'Burn Surgery',
                'Cardiac Surgery',
                'Colorectal Surgery',
                'Esophageal And Gastrointestinal Surgery',
                'Head And Neck Surgery',
                'Hepatobiliary Surgery',
                'Minimally Invasive Surgery',
                'Organ Transplantation And Immunology',
                'Organ Transplantation And Immunology (Kidney)',
                'Organ Transplantation And Immunology (Liver)',
                'Organ Transplantation And Immunology (Pancreas)',
                'Pediatric Cardiovascular Surgery',
                'Pediatric Surgery',
                'Plastic And Reconstructive Surgery',
                'Robotic And Minimally Invasive Surgery',
                'Surgical Critical Care',
                'Surgical Oncology',
                'Thoracic Surgery',
                'Trauma Surgery',
                'Vascular Surgery',
            ],
            'Urology' => [
                'Endourology',
                'Female Urology',
                'Laparoscopic Urology',
                'Male Infertility/Andrology',
                'Neurourology And Incontinence',
                'Pediatric Urology',
                'Renal Transplant Surgery',
                'Robotic And Minimally Invasive Urology',
                'Urologic Oncology',
            ],

        ];

        foreach ($specialties as $specialtyName => $subspecialties) {
            $specialtyId = (string) Str::uuid();

            DB::table('specialties')->insert([
                'id'            => $specialtyId,
                'name'          => $specialtyName,
                'slug'          => Str::slug($specialtyName),
                'created_at'    => $now,
            ]);

            foreach ($subspecialties as $subName) {
                DB::table('sub_specialties')->insert([
                    'id'            => (string) Str::uuid(),
                    'specialty_id'  => $specialtyId,
                    'name'          => $subName,
                    'slug'          => Str::slug($subName),
                    'created_at'    => $now,
                ]);
            }
        }
    }
}
